### ISSUE TITLE
Released firmware doesn't do anything on my Pico nor Pico W

### ISSUE THREAD

**Issue by shreeve** [picoruby/R2P2#3]
When I copy the `*.uf2` firmware file from the latest [Sep 18, 2023 release](https://github.com/picoruby/R2P2/releases), on Raspberry Pi Pico and Pico W boards and replugging in the board after flashing it, I can't see any devices show up in `/dev/cu.usb*`. In effect, I have no way to communicate with the board after flashing it. Since I am just doing the most basic operation on both the Pico and Pico W boards, it seems anyone else would have the same issue. I'm on macOS also, which doesn't seem to be able to build new firmware.

Would someone here be able to generate and release new firmware, which has been confirmed to work? Thank you!

**Comment by hasumikin** [comment]
We have received some reports that R2P2 does not work on macOS. However, we are unsure what kind of mac this issue occurs on.
I don't have a mac so I am not willing to investigate it, sorry
